import { Inter } from "next/font/google";
import "./globals.css";
// import Authprovider from "@/components/authprovider/Authprovider";
import Authprovider from "../components/authprovider/Authprovider";
import { Providers } from "./redux/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shardmind AI",
  description: "Generated by Shaiadul Basar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Authprovider>
          <Providers>{children}</Providers>
        </Authprovider>
      </body>
    </html>
  );
}
