import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./redux/providers";
import { AuthContextProvider } from "../components/authprovider/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shardmind AI",
  description: "Generated by Shaiadul Basar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Providers>{children}</Providers>
        </AuthContextProvider>
      </body>
    </html>
  );
}
